### ISSUE TITLE
Is there a way to use it dynamically?

### ISSUE THREAD

**Issue by rbenitezpagan** [MihajloNesic/jekyll-pdf-embed#2]
## Front Matter
```
---
pdf: true
pdf_url: "link_to_file.pdf"
---
```

## Layout and Liquid Tags
```liquid
{% if page.pdf == true %}
    <h4>PDF</h4>
    {% pdf "{{ page.pdf_url }}" %}
{% endif %}
```

## Result
> Liquid Exception: ERROR:file_not_allowed in /_layouts/{NAME}.html
jekyll 3.9.0 | Error:  ERROR:file_not_allowed
/github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-pdf-embed-1.0.4/lib/jekyll-pdf-embed.rb:19:in `render': ERROR:file_not_allowed (ArgumentError)

## Questions
1. Is there a particular reason as to why the plugin checks for `".pdf\"" | ".ppt\""` and not `".pdf" | ".ppt"` other than being the closing symbol?
2. Is there a smart way to use this plugin dynamically?
3. Is there something I am doing wrong that I am not aware of?

Thanks @MihajloNesic is a great plugin when used as:
```
{% pdf "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" %}
```

**Comment by MihajloNesic** [comment]
Hi @rbenitezpagan. Thank you for using the plugin!

There is an issue on how the plugin is extracting the url and extensions, thus the front matter approach is not working as hoped. This is something I will consider fixing in a future version, so thank you for reporting!

The reason there is an escaped double quote for both file extensions is that I used regex to extract url, that is between two double quotes. For some reason, extracting the extension counted the last double quote. That part of the code will be refactored in the new release.

**Comment by MihajloNesic** [comment]
Front matter is supported in version 1.1.0 (from commit https://github.com/MihajloNesic/jekyll-pdf-embed/commit/20a2a709c41b797cfa5756a7b9253e2fe92855e1).


Here's a page for all of the examples [https://mihajlonesic.gitlab.io/jpe-examples/](https://mihajlonesic.gitlab.io/jpe-examples/)
