### ISSUE TITLE
how can i set the height of the embedded frame?

### ISSUE THREAD

**Issue by shubhams** [MihajloNesic/jekyll-pdf-embed#3]
The embedded PDF window is too short when using:

```markdown
---
pdf_file: "/assets/pdf/example_pdf.pdf"
title: example
---

{% pdf {{ page.pdf_file}} %}

```

Is there a way I can specify the height of the embedded frame?

![Screen Shot 2021-01-19 at 3 07 51 PM](https://user-images.githubusercontent.com/6473299/105093296-1cba4480-5a68-11eb-8de2-615fc974d4ed.png)

**Comment by MihajloNesic** [comment]
Hi @shubhams, thank you for using the plugin.

Currently, there is no way to specify the height of the iframe. This is something that will be added in a future version.
I can't predict when will this be implemented. When it does, I'll comment and close this issue.

**Comment by MihajloNesic** [comment]
Custom size is supported in version 1.1.1 (from commit https://github.com/MihajloNesic/jekyll-pdf-embed/commit/841c961dfee123ad7c0f92c78045d52f9f3d68f1).

Example usage: 
```
{% pdf "/files/pdf/sample.pdf" width=50% height=500px %}
```

Here's a page for all of the examples [https://mihajlonesic.gitlab.io/jpe-examples/](https://mihajlonesic.gitlab.io/jpe-examples/)
