### ISSUE TITLE
Cannot use in GitHub Pages?

### ISSUE THREAD

**Issue by loikein** [MihajloNesic/jekyll-pdf-embed#4]
Hi, I know that builing locally would be an option, but when letting GitHub to build, this message showed up:

Is there any way to work around it (except builing locally)? Thank you very much.

```text
GitHub Pages failed to build your site.

The tag pdf on line 1 in _pages/CV.md is not a recognized Liquid tag.
```

**Comment by loikein** [comment]
I am sorry to post repetitive issue. It is really a shame to know.

**Comment by MihajloNesic** [comment]
Thank you for using the plugin. 

It is a shame that GitHub isn't allowing 'third party' plugins. Untill they change their mind, there is no other way to use plugins, except building them locally.

**Comment by loikein** [comment]
On that note, I found this action that seems to allow switchin off safe building, but was too lazy to try it out…

[EdricChan03/action-build-deploy-ghpages](https://github.com/EdricChan03/action-build-deploy-ghpages)
