### ISSUE TITLE
Liquid syntax error: Unknown tag 'pdf' on build

### ISSUE THREAD

**Issue by guslipkin** [MihajloNesic/jekyll-pdf-embed#7]
Hello. I was really excited to find and implement this and was able to do so pretty quickly, but for a few small errors. 

If I tried to install with `gem install jekyll-pdf-embed` I would get an error that 

> Liquid Exception: Liquid syntax error (line 1): Unknown tag 'pdf' in [my file name]

When I changed to using 

```
group :jekyll_plugins do
  gem "jekyll-pdf-embed"
end

bundle
```

it works locally just fine. However, when I upload to GitHub and go to deploy, neither method works and I get the same error.

**Comment by MihajloNesic** [comment]
Hello @guslipkin. Thank you for using this plugin.

GitHub does not support all plugins. According to the docs:
> GitHub Pages cannot build sites using unsupported plugins. If you want to use unsupported plugins, generate your site locally and then push your site's static files to GitHub Enterprise.

See #1 for more detailed explanation

There is a workaround. You can use [jekyll-deploy-action](jekyll-deploy-action) to deploy your Jekyll site with any plugin. Here is [my implementation](https://github.com/MihajloNesic/minimal-mistakes-pdf-example).

**Comment by liver121888** [comment]
Hi, I met with the same problem, but the error remained after I followed the instruction.
https://github.com/liver121888/liver121888.github.io
I additionally added the exclude: [vendor] in my file to solve the issue described in 
https://github.com/jekyll/jekyll/issues/2938

**Comment by MihajloNesic** [comment]
Hi @liver121888, 
I'm not sure why your deployment is not working. I've created another repo to test the deployment of Jekyll website with jekyll-pdf-embed plugin and everything works as expected -> https://github.com/MihajloNesic/jekyll-pdf-embed-starter

**Comment by liver121888** [comment]
Ok, this is very weird.
Initially, I included the below in the markdown post.
{% pdf "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" %}.
Then the build fails.
But I looked up the HTML generated locally and past the entire HTML into the markdown post, and it works.
```HTML
<style> .pdf-embed-wrap-87f43424-063f-4e2e-8f19-5bdf01cb7be0 { display:flex; flex-direction: column; width: 100%; height: 650px; } .pdf-embed-container-87f43424-063f-4e2e-8f19-5bdf01cb7be0 { height: 100%; } .pdf-link-87f43424-063f-4e2e-8f19-5bdf01cb7be0 { background-color: white; text-align: center; border-style: solid; } .pdf-embed-container-87f43424-063f-4e2e-8f19-5bdf01cb7be0 iframe { width: 100%; height: 100%; } </style>
<div class="pdf-embed-wrap-87f43424-063f-4e2e-8f19-5bdf01cb7be0"> <div class="pdf-link-87f43424-063f-4e2e-8f19-5bdf01cb7be0"> <a href="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" target="_blank">View PDF</a> </div> <div class="pdf-embed-container-87f43424-063f-4e2e-8f19-5bdf01cb7be0"> <iframe src="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" frameborder="0" allowfullscreen=""></iframe> </div> </div>
```
Will this information help you understand the problem?
Any help is appreciated.

**Comment by liver121888** [comment]
Also, if I want to link to a pdf that's in another repository, the link seems not working.
https://github.com/liver121888/NTUBME-2021-MechatronicsIV-FinalProject/blob/master/MechatronicsIV.pdf
It will show: GitHub refuses to establish the connection.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/68542467/206617701-f469ea8a-0d35-4137-8f3b-93ce6ca25dab.png">

**Comment by liver121888** [comment]
My workaround for this problem is to publish that repo as a site under my github.io. Hope this helps those who want to access files in a different repo.

**Comment by MihajloNesic** [comment]
@liver121888 The different repo "issue" is because that repo is private (I cannot access it). As for the other issue, it is regarding your deployment, and not this plugin
